grid:
  x_delta: 5.0e-4
  count: 2048
beam:
  spot_size: 0.05
  wavelength: 1.0e-6
turbulence:
  kolmogorov:
    cn2: 1.0e-13
  atmosphere:
    distance: 2500
    phase_screen_count: 4
lens:
  focal_length: 0.25