# experiment 1
grid:
  x_delta: 5.0e-4
  count: 2048
beam:
  spot_size: 0.05
  wavelength: 1.0e-6
  radius: 0.2
  focus: 2500
turbulence:
  kolmogorov:
    cn2: 1.0e-14
  atmosphere:
    distance: 2500
    phase_screen_count: 4
lens:
  focal_length: 0.25
spatial_light_modulator:
  element_length: 0.02
  element_count: 20
  perturbation_mag: 3.14e-2
  learning_rate: 5.0e-4