# Phase conjugate test
grid:
  x_delta: 5.0e-4
  count: 2048
beam:
  spot_size: 0.05
  wavelength: 1.0e-6
  radius: 0.2
turbulence:
  kolmogorov:
    cn2: 1.0e-14
  atmosphere:
    distance: 2000
    phase_screen_count: 4
